/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedOnboardedRouteRouteImport } from './routes/_authed/_onboarded/route'
import { Route as PublicSignUpIndexRouteImport } from './routes/_public/sign-up/index'
import { Route as PublicSignInIndexRouteImport } from './routes/_public/sign-in/index'
import { Route as AuthedOnboardingIndexRouteImport } from './routes/_authed/onboarding/index'
import { Route as AuthedOnboardedHomeRouteRouteImport } from './routes/_authed/_onboarded/_home/route'
import { Route as AuthedOnboardedHomeIndexRouteImport } from './routes/_authed/_onboarded/_home/index'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardedRouteRoute = AuthedOnboardedRouteRouteImport.update({
  id: '/_onboarded',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const PublicSignUpIndexRoute = PublicSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignInIndexRoute = PublicSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedOnboardingIndexRoute = AuthedOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOnboardedHomeRouteRoute =
  AuthedOnboardedHomeRouteRouteImport.update({
    id: '/_home',
    getParentRoute: () => AuthedOnboardedRouteRoute,
  } as any)
const AuthedOnboardedHomeIndexRoute =
  AuthedOnboardedHomeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOnboardedHomeRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedOnboardedHomeIndexRoute
  '/onboarding/': typeof AuthedOnboardingIndexRoute
  '/sign-in/': typeof PublicSignInIndexRoute
  '/sign-up/': typeof PublicSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedOnboardedHomeIndexRoute
  '/onboarding': typeof AuthedOnboardingIndexRoute
  '/sign-in': typeof PublicSignInIndexRoute
  '/sign-up': typeof PublicSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authed/_onboarded': typeof AuthedOnboardedRouteRouteWithChildren
  '/_authed/_onboarded/_home': typeof AuthedOnboardedHomeRouteRouteWithChildren
  '/_authed/onboarding/': typeof AuthedOnboardingIndexRoute
  '/_public/sign-in/': typeof PublicSignInIndexRoute
  '/_public/sign-up/': typeof PublicSignUpIndexRoute
  '/_authed/_onboarded/_home/': typeof AuthedOnboardedHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboarding/' | '/sign-in/' | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/_onboarded'
    | '/_authed/_onboarded/_home'
    | '/_authed/onboarding/'
    | '/_public/sign-in/'
    | '/_public/sign-up/'
    | '/_authed/_onboarded/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_onboarded': {
      id: '/_authed/_onboarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedOnboardedRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_public/sign-up/': {
      id: '/_public/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof PublicSignUpIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-in/': {
      id: '/_public/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof PublicSignInIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/onboarding/': {
      id: '/_authed/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthedOnboardingIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_onboarded/_home': {
      id: '/_authed/_onboarded/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedOnboardedHomeRouteRouteImport
      parentRoute: typeof AuthedOnboardedRouteRoute
    }
    '/_authed/_onboarded/_home/': {
      id: '/_authed/_onboarded/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedOnboardedHomeIndexRouteImport
      parentRoute: typeof AuthedOnboardedHomeRouteRoute
    }
  }
}

interface AuthedOnboardedHomeRouteRouteChildren {
  AuthedOnboardedHomeIndexRoute: typeof AuthedOnboardedHomeIndexRoute
}

const AuthedOnboardedHomeRouteRouteChildren: AuthedOnboardedHomeRouteRouteChildren =
  {
    AuthedOnboardedHomeIndexRoute: AuthedOnboardedHomeIndexRoute,
  }

const AuthedOnboardedHomeRouteRouteWithChildren =
  AuthedOnboardedHomeRouteRoute._addFileChildren(
    AuthedOnboardedHomeRouteRouteChildren,
  )

interface AuthedOnboardedRouteRouteChildren {
  AuthedOnboardedHomeRouteRoute: typeof AuthedOnboardedHomeRouteRouteWithChildren
}

const AuthedOnboardedRouteRouteChildren: AuthedOnboardedRouteRouteChildren = {
  AuthedOnboardedHomeRouteRoute: AuthedOnboardedHomeRouteRouteWithChildren,
}

const AuthedOnboardedRouteRouteWithChildren =
  AuthedOnboardedRouteRoute._addFileChildren(AuthedOnboardedRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedOnboardedRouteRoute: typeof AuthedOnboardedRouteRouteWithChildren
  AuthedOnboardingIndexRoute: typeof AuthedOnboardingIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedOnboardedRouteRoute: AuthedOnboardedRouteRouteWithChildren,
  AuthedOnboardingIndexRoute: AuthedOnboardingIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicSignInIndexRoute: typeof PublicSignInIndexRoute
  PublicSignUpIndexRoute: typeof PublicSignUpIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSignInIndexRoute: PublicSignInIndexRoute,
  PublicSignUpIndexRoute: PublicSignUpIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
